language: python
python:
  - "3.6"

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial  # Required for Python 3.7
      sudo: true    # travis-ci/travis-ci#9069
    - python: 3.6
      dist: trusty

cache:
  directories:
   - $HOME/.cache/pip

install:
  - travis_retry pip install -r requirements/requirements.txt
  - travis_retry pip install -r requirements/test_requirements.txt
  - python setup.py develop

script:
  - pytest --cov=. --cov-report term-missing tests/ 
  - coverage xml -i

after_success:
  - coveralls
  - codeclimate-test-reporter
  - python-codacy-coverage -r coverage.xml
