language: python
python:
  - "3.5"
  - "3.6"

before_install:
  - travis_retry sudo apt-get update
  - travis_retry wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

cache:
  directories:
   - $HOME/.cache/pip

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment

  - travis_retry pip install -r requirements/requirements.txt
  - travis_retry pip install -r requirements/test_requirements.txt
  - python setup.py develop

script:
  - pytest --cov=. --cov-report term-missing tests/ 
  - coverage xml

after_success:
  - coveralls
  - codeclimate-test-reporter
  - python-codacy-coverage -r coverage.xml
